# services:
#   - type: web
#     name: portfolio-backend
#     env: node
#     rootDirectory: portfolio-fullstack/backend
#     buildCommand: npm install && npm run build
#     startCommand: npm run start:prod
#     envVars:
#       - key: NODE_ENV
#         value: production
#       - key: PORT
#         value: 10000

services:
  - type: web
    name: portfolio-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
